### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by jamelt** [hexojs/hexo-util#19]
syntax highlighting will definitely not work out of the box for highlight.js. the code does not have the necessary bits in place

**Comment by NoahDragon** [comment]
Could you please elaborate?

**Comment by jamelt** [comment]
Take a look at the [highlight.js stylesheets](https://github.com/isagalaev/highlight.js/tree/master/src/styles)
...
``` css
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: white;
  color: black;
}

.hljs-string,
.hljs-variable,
.hljs-template-variable,
.hljs-symbol,
.hljs-bullet,
.hljs-section,
.hljs-addition,
.hljs-attribute,
.hljs-link {
  color: #888;
}
```
...

All of the CSS classes have the prefix ``hljs-``

The highlight.js file does not set the class prefix. It is impossible for any of these styles to work.

https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L8
``` javascript
hljs.configure({
  classPrefix: ''
});
```

Finally, the root class that applies the syntax background ``hljs`` is not appended to the code generation block.

https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L41
``` javascript
result += '<figure class="highlight' + (data.language ? ' ' + data.language : '') + '">';
```
